### ISSUE TITLE
RGCN branch

### ISSUE THREAD

**Issue by code-rex1** [graph4ai/graph4nlp#546] opened 2022-04-03 06:47 UTC
## ❓ Questions and Help

Thanks for this great library. I am greatly interested to try out the RGCN graph.

I see there are two branches:

1. https://github.com/graph4ai/graph4nlp/commits/rgcn 
2. https://github.com/graph4ai/graph4nlp/tree/rgcn_graphdata

It appears RGCN work is still in the progress. But I am more than happy to try out and beta-testing the RGCN graph for an NMT task.

Any help is appreciated @SaizhuoWang @xiao03 🙏

**Comment by xiao03** [comment] 2022-04-03 14:14
Hi @code-rex1, Thanks for your interest in our work. Currently RGCN work is still in progress and the code may not run as intended. Please be patient and we will announce our progress as soon as possible.

Meanwhile, I'm closing this issue as it is about something in active developing and at the current stage we cannot provide any support regarding it.

**Closed by xiao03** 2022-04-03 14:14 UTC
